version: "3.7"
services:
  postgres:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 15432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host
volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_net
    driver: bridge


    


      